#time in seconds
refresh: 30
repositories:
  - name: release
    sync: true
    force: true
    url: git@github.com:ovrdoz/release.git
    script: |
      #!/bin/bash
      echo "hello i'm repoear.io"
